### ISSUE TITLE
[Feature] Smarter, smaller builds

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/tools#1176]
## TODO:
- [x] 1. Stream starts with src/ directory instead of all files, can be changed via user-input globs
- [x] 2. Dependencies stream involves reading the source stream and parsing the dependency tree via hydrolosis
- [x] 3. If dependency is found, file is pushed into the top of the build pipeline stream
#### For 3:

This requires that all files are compiled and present at the start of build pipeline, or that there's a fallback process if file does not exist (assumes it will exist in the future). Possible implementations:
- Force "compilation" step to complete before the build pipeline starts. Ex: run typescript and start build pipeline after all files are created. If we can rely on this assumption, then we can throw an error when a file is not found. Less moving pieces, but also less efficient.
- Handle not found files by putting them into a queue and retrying later. Once all pipeline steps before read are complete, retry the files in this queue. Throw an error if they aren't found at this point. This allows for compilation of all non-html files, but would fail if the imports/loading graph changes during "compilation". More efficient, but puts the restriction on HTML files that they cannot be modified during "compilation". 

@justinfagnani thoughts on this tradeoff? Are we okay with allowing some files to be changed during "compilation" but breaking on certain types of changes (related to HTML files and the imports/scripts/styles loading graph it creates). I'd rather encourage an explicit "before build" step that prepares the target for polymer-build vs. modifying files during read.
