### ISSUE TITLE
Support ES6 modules

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#1573]
Creating a tracking bug for this.

TODOs
- [x] Create JavaScriptScriptParser and JavaScriptModuleParser to replace uses of JavaScriptParser for use with any case where we already know the type (i.e. `<script type=module>` should only leverage JavaScriptModuleParser). #732
- [x] Wire in the JS import scanner and resolve scripts etc, so imported documents are loaded transitively. #733
- [ ] Store imported identifiers/names.  Consider using a new special scope object for this task and define *separate* scope objects for (right now there's just one layer):
  - [ ] Custom element tag names
  - [ ] Global/namespaced javascript identifiers
  - [ ] Exported JS identifiers
  - [ ] Imported JS identifiers
- [ ] Create an `export` scanner for module js.
- [ ] Investigate whether url resolver interface would be sufficient for resolving relative node package names.
- [ ] Consider differentiating the reference type for the script: `html-script` (was with type=module or not, or imported from a module).  At cache level, include module type in the key.
- [x] Consider a separate dynamic import scanner or model with the `.lazy` behavior of `html-import` feature. Issue #740
- [x] Consider switching out the js parser to babylon (better support for scope analysis also typescript)
- [ ] Add modules to analysis generation https://github.com/Polymer/polymer-analyzer/issues/747
- [ ] Module imports need their own specifier resolution hook, possibly separate from UrlResolver.
